image: pointsofinterest/gitlabr:latest

document:
  stage: document
  script:
  - R --vanilla -e ' library(devtools); devtools::document(); devtools::document()'
  artifacts:
   paths:
   - man/
   - NAMESPACE

test:
  stage: test
  dependencies: 
  - document
  script:
  - R --vanilla -e ' library(devtools); library(testthat); devtools::test(reporter
    = StopReporter)'

build:
  stage: build
  script:
  - R --vanilla -e ' library(devtools); devtools::build(path = "./")'
  artifacts:
    paths:
    - '*.tar.gz'

check:
  stage: check
  script:
  - R --vanilla -e ' library(devtools); devtools::check_built()'

stages:
- document
- test
- build
- check

