image: rocker/r-devel:latest

prepare:
  stage: prepare
  script:
  - apt-get install -y libssl-dev
  - R --vanilla -e ' if (!require(devtools)) { install.packages("devtools", repos
    = "https://cran.rstudio.com"); library(devtools); }; devtools::install_dev_deps()'

document:
  stage: document
  script:
  - R --vanilla -e ' library(devtools); devtools::document(); devtools::document()'

test:
  stage: test
  script:
  - R --vanilla -e ' library(devtools); devtools::test(reporter = StopReporter())'

build:
  stage: build
  script:
  - R --vanilla -e ' library(devtools); devtools::build(path = "./")'
  artifacts:
    paths:
    - '*.tar.gz'

check:
  stage: check
  script:
  - R --vanilla -e ' library(devtools); devtools::check_built()'

stages:
- prepare
- document
- test
- build
- check

