# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
before_script:
  - R --vanilla -e 'library(devtools);  devtools::document(); devtools::document()'
  - R --vanilla -e 'library(devtools); library(testthat); devtools::test(reporter
    = StopReporter)'

